server: 
  port: 1113
#spring:
  #application:
    #name: service-1113
# 开启熔断功能
feign: 
   hystrix: 
      enabled: true
### spring 配置
spring:
  ##  zipkin 链路跟踪配置
  sleuth:
    enabled: true
    #采样率，越高会有性能影响
    sampler:
      percentage: 1.0
  cloud:
    ## kafka zk配置 配合zipkin
    stream:
      kafka:
        binder:
          brokers: 192.168.206.203:9092
          zkNodes: 192.168.206.203:2181